CREATE TABLE IF NOT EXISTS games (
  slug TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  year_published INTEGER,
  bgg_id INTEGER UNIQUE,
  bgg_rating NUMERIC(4, 2),
  bgg_rank INTEGER,
  bgg_weight NUMERIC(4, 2),
  bgg_num_ratings INTEGER NOT NULL DEFAULT 0,
  min_players INTEGER NOT NULL DEFAULT 1,
  max_players INTEGER NOT NULL DEFAULT 1,
  best_player_counts INTEGER[] NOT NULL DEFAULT '{}',
  playing_time_min INTEGER,
  playing_time_max INTEGER,
  min_age INTEGER,
  dna_strategy NUMERIC(5, 2),
  dna_luck NUMERIC(5, 2),
  dna_interaction NUMERIC(5, 2),
  dna_complexity NUMERIC(5, 2),
  dna_length NUMERIC(5, 2),
  dna_scaling NUMERIC(5, 2),
  dna_replayability NUMERIC(5, 2),
  dna_accessibility NUMERIC(5, 2),
  wikidata_id TEXT NOT NULL DEFAULT '',
  thumbnail_url TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL DEFAULT '',
  is_featured BOOLEAN NOT NULL DEFAULT false,
  is_expansion BOOLEAN NOT NULL DEFAULT false,
  description TEXT NOT NULL DEFAULT '',
  meta_description TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'postgres'
);

CREATE INDEX IF NOT EXISTS games_featured_idx ON games (is_featured, is_expansion);
CREATE INDEX IF NOT EXISTS games_rank_idx ON games (bgg_rank);
CREATE INDEX IF NOT EXISTS games_name_idx ON games (lower(name));

CREATE TABLE IF NOT EXISTS categories (
  slug TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  bgg_id INTEGER,
  category_type TEXT NOT NULL DEFAULT 'style',
  game_count INTEGER NOT NULL DEFAULT 0,
  meta_description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS mechanics (
  slug TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  bgg_id INTEGER,
  parent_slug TEXT,
  depth INTEGER NOT NULL DEFAULT 0,
  complexity_tendency TEXT NOT NULL DEFAULT 'mixed',
  game_count INTEGER NOT NULL DEFAULT 0,
  meta_description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS progression_paths (
  slug TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  difficulty_start TEXT NOT NULL DEFAULT '',
  difficulty_end TEXT NOT NULL DEFAULT '',
  target_audience TEXT NOT NULL DEFAULT '',
  primary_mechanic_slug TEXT,
  primary_category_slug TEXT,
  meta_description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS game_night_themes (
  slug TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  player_count_min INTEGER NOT NULL DEFAULT 1,
  player_count_max INTEGER NOT NULL DEFAULT 1,
  duration_hours TEXT NOT NULL DEFAULT '',
  vibe TEXT NOT NULL DEFAULT '',
  playlist_concept TEXT NOT NULL DEFAULT '',
  meta_description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS tools (
  slug TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  tool_type TEXT NOT NULL DEFAULT '',
  icon TEXT NOT NULL DEFAULT '',
  is_published BOOLEAN NOT NULL DEFAULT true,
  meta_description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS profiles (
  id INTEGER PRIMARY KEY REFERENCES app_users(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  experience_level TEXT NOT NULL DEFAULT 'beginner',
  preferred_players INTEGER NOT NULL DEFAULT 1,
  max_play_time INTEGER NOT NULL DEFAULT 60,
  bio TEXT NOT NULL DEFAULT '',
  favorite_genres TEXT[] NOT NULL DEFAULT '{}'
);

DELETE FROM profiles
WHERE NOT EXISTS (
  SELECT 1 FROM app_users WHERE app_users.id = profiles.id
);

ALTER TABLE profiles
  DROP CONSTRAINT IF EXISTS profiles_id_fkey;

ALTER TABLE profiles
  ADD CONSTRAINT profiles_id_fkey
  FOREIGN KEY (id) REFERENCES app_users(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lobby_id INTEGER,
  game_slug TEXT NOT NULL,
  game_name TEXT NOT NULL,
  title TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  session_mood TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  would_replay BOOLEAN NOT NULL DEFAULT true,
  played_at DATE NOT NULL,
  players_count INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS reviews_played_at_idx ON reviews (played_at DESC);
CREATE INDEX IF NOT EXISTS reviews_game_slug_idx ON reviews (game_slug);

ALTER TABLE reviews
  ADD COLUMN IF NOT EXISTS lobby_id INTEGER;

CREATE INDEX IF NOT EXISTS reviews_lobby_idx ON reviews (lobby_id);

CREATE TABLE IF NOT EXISTS local_catalog_meta (
  id INTEGER PRIMARY KEY,
  source TEXT NOT NULL,
  source_url TEXT NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL,
  games INTEGER NOT NULL DEFAULT 0,
  featured_games INTEGER NOT NULL DEFAULT 0,
  mechanics INTEGER NOT NULL DEFAULT 0,
  categories INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS players (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL DEFAULT '',
  skill_level TEXT NOT NULL DEFAULT 'casual',
  rating INTEGER NOT NULL DEFAULT 1000,
  games_played INTEGER NOT NULL DEFAULT 0,
  wins INTEGER NOT NULL DEFAULT 0,
  is_friend BOOLEAN NOT NULL DEFAULT false,
  avatar_color TEXT NOT NULL DEFAULT '#153d45',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS players_rating_idx ON players (rating DESC);
CREATE INDEX IF NOT EXISTS players_friend_idx ON players (is_friend);

CREATE TABLE IF NOT EXISTS app_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  city TEXT NOT NULL DEFAULT '',
  skill_level TEXT NOT NULL DEFAULT 'casual',
  rating INTEGER NOT NULL DEFAULT 1000,
  games_played INTEGER NOT NULL DEFAULT 0,
  wins INTEGER NOT NULL DEFAULT 0,
  avatar_color TEXT NOT NULL DEFAULT '#153d45',
  friend_code TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE app_users
  ADD COLUMN IF NOT EXISTS email TEXT;

UPDATE app_users
SET email = username || '@example.com'
WHERE email IS NULL OR email = '';

ALTER TABLE app_users
  ALTER COLUMN email SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS app_users_email_idx ON app_users (lower(email));
CREATE INDEX IF NOT EXISTS app_users_rating_idx ON app_users (rating DESC);
CREATE INDEX IF NOT EXISTS app_users_friend_code_idx ON app_users (friend_code);

CREATE TABLE IF NOT EXISTS auth_sessions (
  token_hash TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS auth_sessions_user_idx ON auth_sessions (user_id);

CREATE TABLE IF NOT EXISTS friendships (
  user_id INTEGER NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  friend_user_id INTEGER NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, friend_user_id),
  CONSTRAINT friendships_no_self CHECK (user_id <> friend_user_id)
);

CREATE TABLE IF NOT EXISTS friend_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_user_id INTEGER NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  to_user_id INTEGER NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  responded_at TIMESTAMPTZ,
  CONSTRAINT friend_requests_no_self CHECK (from_user_id <> to_user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS friend_requests_pending_unique
  ON friend_requests (from_user_id, to_user_id)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS friend_requests_to_user_idx ON friend_requests (to_user_id, status);

CREATE TABLE IF NOT EXISTS lobbies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE,
  game_slug TEXT REFERENCES games(slug) ON DELETE SET NULL,
  name TEXT NOT NULL DEFAULT 'Игровой вечер',
  status TEXT NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE lobbies
  ADD COLUMN IF NOT EXISTS owner_user_id INTEGER REFERENCES app_users(id) ON DELETE CASCADE;

ALTER TABLE lobbies
  ADD COLUMN IF NOT EXISTS game_slug TEXT REFERENCES games(slug) ON DELETE SET NULL;

ALTER TABLE reviews
  ADD COLUMN IF NOT EXISTS lobby_id INTEGER;

ALTER TABLE reviews
  DROP CONSTRAINT IF EXISTS reviews_lobby_id_fkey;

ALTER TABLE reviews
  ADD CONSTRAINT reviews_lobby_id_fkey
  FOREIGN KEY (lobby_id) REFERENCES lobbies(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS lobby_members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lobby_id INTEGER NOT NULL REFERENCES lobbies(id) ON DELETE CASCADE,
  player_id INTEGER REFERENCES players(id) ON DELETE SET NULL,
  user_id INTEGER REFERENCES app_users(id) ON DELETE SET NULL,
  guest_name TEXT,
  is_guest BOOLEAN NOT NULL DEFAULT false,
  seat_order INTEGER NOT NULL DEFAULT 0,
  placement INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT lobby_member_has_name CHECK (
    player_id IS NOT NULL OR user_id IS NOT NULL OR guest_name IS NOT NULL
  )
);

ALTER TABLE lobby_members
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES app_users(id) ON DELETE SET NULL;

ALTER TABLE lobby_members
  ADD COLUMN IF NOT EXISTS placement INTEGER;

ALTER TABLE lobby_members
  DROP CONSTRAINT IF EXISTS lobby_member_has_name;

ALTER TABLE lobby_members
  ADD CONSTRAINT lobby_member_has_name CHECK (
    player_id IS NOT NULL OR user_id IS NOT NULL OR guest_name IS NOT NULL
  );

CREATE INDEX IF NOT EXISTS lobby_members_lobby_idx ON lobby_members (lobby_id, seat_order);

CREATE TABLE IF NOT EXISTS game_sessions (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  theme TEXT NOT NULL,
  genre TEXT NOT NULL DEFAULT '',
  tone TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft',
  current_phase TEXT NOT NULL DEFAULT 'character_creation',
  current_scene TEXT NOT NULL DEFAULT '',
  current_actor_id TEXT,
  turn_mode BOOLEAN NOT NULL DEFAULT false,
  scene_type TEXT NOT NULL DEFAULT 'preparation',
  round INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS game_sessions_status_idx ON game_sessions (status, updated_at DESC);

CREATE TABLE IF NOT EXISTS game_states (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL UNIQUE REFERENCES game_sessions(id) ON DELETE CASCADE,
  public_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  hidden_gm_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  map_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  summary_short TEXT NOT NULL DEFAULT '',
  summary_long TEXT NOT NULL DEFAULT '',
  important_facts_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  unresolved_threads_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS game_characters (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES game_sessions(id) ON DELETE CASCADE,
  player_id TEXT NOT NULL,
  name TEXT NOT NULL,
  race TEXT NOT NULL DEFAULT '',
  class_name TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  background TEXT NOT NULL DEFAULT '',
  goal TEXT NOT NULL DEFAULT '',
  strength TEXT NOT NULL DEFAULT '',
  weakness TEXT NOT NULL DEFAULT '',
  secret TEXT NOT NULL DEFAULT '',
  stats_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  hp_current INTEGER NOT NULL DEFAULT 10,
  hp_max INTEGER NOT NULL DEFAULT 10,
  inventory_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  status_effects_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  location_id TEXT,
  x NUMERIC(10, 2) NOT NULL DEFAULT 100,
  y NUMERIC(10, 2) NOT NULL DEFAULT 100,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS game_characters_session_idx ON game_characters (session_id);
CREATE INDEX IF NOT EXISTS game_characters_player_idx ON game_characters (player_id, session_id);

CREATE TABLE IF NOT EXISTS game_npcs (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES game_sessions(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT '',
  personality TEXT NOT NULL DEFAULT '',
  goal TEXT NOT NULL DEFAULT '',
  knows_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  secret TEXT NOT NULL DEFAULT '',
  attitude TEXT NOT NULL DEFAULT '',
  location_id TEXT,
  x NUMERIC(10, 2) NOT NULL DEFAULT 100,
  y NUMERIC(10, 2) NOT NULL DEFAULT 100,
  visible_to_players BOOLEAN NOT NULL DEFAULT true,
  state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS game_npcs_session_idx ON game_npcs (session_id, visible_to_players);

CREATE TABLE IF NOT EXISTS game_messages (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES game_sessions(id) ON DELETE CASCADE,
  player_id TEXT,
  character_id TEXT,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  visible_to_players BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS game_messages_session_idx ON game_messages (session_id, created_at ASC);

CREATE TABLE IF NOT EXISTS game_quests (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES game_sessions(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active',
  known_to_players BOOLEAN NOT NULL DEFAULT true,
  state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS game_quests_session_idx ON game_quests (session_id, status);

CREATE TABLE IF NOT EXISTS game_maps (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES game_sessions(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  image_url TEXT NOT NULL DEFAULT '',
  width INTEGER NOT NULL DEFAULT 2000,
  height INTEGER NOT NULL DEFAULT 1200,
  grid_enabled BOOLEAN NOT NULL DEFAULT false,
  grid_cell_size INTEGER NOT NULL DEFAULT 50,
  map_type TEXT NOT NULL DEFAULT 'region_or_location',
  fog_of_war BOOLEAN NOT NULL DEFAULT false,
  state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS game_maps_session_idx ON game_maps (session_id);

CREATE TABLE IF NOT EXISTS game_map_objects (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES game_sessions(id) ON DELETE CASCADE,
  map_id TEXT NOT NULL REFERENCES game_maps(id) ON DELETE CASCADE,
  object_type TEXT NOT NULL,
  ref_id TEXT,
  name TEXT NOT NULL DEFAULT '',
  x NUMERIC(10, 2) NOT NULL DEFAULT 0,
  y NUMERIC(10, 2) NOT NULL DEFAULT 0,
  width NUMERIC(10, 2) NOT NULL DEFAULT 40,
  height NUMERIC(10, 2) NOT NULL DEFAULT 40,
  visible_to_players BOOLEAN NOT NULL DEFAULT true,
  locked BOOLEAN NOT NULL DEFAULT false,
  state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS game_map_objects_map_idx ON game_map_objects (map_id, visible_to_players);

CREATE TABLE IF NOT EXISTS game_turns (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES game_sessions(id) ON DELETE CASCADE,
  round INTEGER NOT NULL DEFAULT 0,
  actor_id TEXT NOT NULL,
  actor_type TEXT NOT NULL DEFAULT 'character',
  turn_index INTEGER NOT NULL DEFAULT 0,
  is_current BOOLEAN NOT NULL DEFAULT false,
  has_acted BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS game_turns_session_idx ON game_turns (session_id, round, turn_index);

CREATE TABLE IF NOT EXISTS game_prompt_security_logs (
  id TEXT PRIMARY KEY,
  session_id TEXT REFERENCES game_sessions(id) ON DELETE CASCADE,
  player_id TEXT,
  character_id TEXT,
  content TEXT NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
